theme: jekyll-theme-slate
title: "EJCyber | Cybersecurity Projects & SOC Lab"
description: "A collection of hands-on cybersecurity projects, including SIEM, threat hunting, incident response, and security automation."
show_downloads: true
github:
  is_project_page: false
